### PR TITLE
RFC: Add type hints

### PR DESCRIPTION
**Pull request by jacopofar**
I decided to use the time my company, [Flixbus](https://www.flixbus.com/), dedicates to FOSS projects to contribute to this package.

This PR adds type hints as described in issue #312 and includes `mypy` in Travis configuration. This means that IDEs can automatically detect type errors and results from static check tools can improve.

There are a few doubts about which I'd like a feedback and for which I'm ready to work to change/fix:

- Mypy complains about `PyJWT.encode` not being a subtype of `PyJWS.encode`, and the same for `decode`. In the case of `decode` the problem is that one calls the token `jwt` and the other `jws`, so I just called both `token`. As for `encode` the problem is that `JWS` expects bytes and `JWT` a dictionary, so I changed `JWS.encode` to `JWS.encode_bytes`. In the documentation there are no examples about using that function, but it is a breaking change for who uses it.

- The change required to import the `typing` module in a `try...catch`, so it can be imported when checking the types but is ignored during normal usage of the library. It's a bit ugly but I couldn't find other ways to have it work on Python 2.7

- I didn't update the changelog or bump the version, if `JWS.encode` is considered part of the API I guess the major version number is affected

### CODE REVIEW

File: jwt/api_jws.py [hunk 1]
```diff
@@ -69,8 +74,13 @@ def get_algorithms(self):
         """
         return list(self._valid_algs)
 
-    def encode(self, payload, key, algorithm='HS256', headers=None,
-               json_encoder=None):
+    def encode_bytes(self,
+                     payload,  # type: bytes
```
Comment (jpadilla) [inline jwt/api_jws.py]: I'm wondering if we could leave this as `.encode()` and make the type for payload `Union[bytes, Dict]`?

Comment (jacopofar) [reply jwt/api_jws.py]: It's possible, doing so mypy says:
 `jwt/api_jwt.py:57: error: Unsupported target for indexed assignment`
because the function is using the payload it as a dictionary. But before that there's a check for it and an error being thrown if it's not so I think it's fine to silence it.

The new commit does that and revert `encode_bytes` to `encode`

File: jwt/api_jwt.py [hunk 2]
```diff
@@ -55,7 +66,12 @@ def encode(self, payload, key, algorithm='HS256', headers=None,
             json_payload, key, algorithm, headers, json_encoder
         )
 
-    def decode(self, jwt, key='', verify=True, algorithms=None, options=None,
```
Comment (aklim007) [inline jwt/api_jwt.py]: change jwt -> token, changes public interface and broken my code

Comment (jacopofar) [reply jwt/api_jwt.py]: Sorry, I didn't see it as a major change as the argument is positional, turns out I was wrong and there are users with the same problem. It has been reverted [here](https://github.com/jpadilla/pyjwt/issues/351)
