### ISSUE TITLE
Issue with PyJWT == 2.0.0

### ISSUE THREAD

**Issue by RakeshRam** [jpadilla/pyjwt#591]
Error occurs when trying to use `mutations.Register.Field()` or `mutations.ObtainJSONWebToken.Field()` when working on 

- graphene-django
- django-graphql-jwt
- django-graphql-auth

Issue occurs only in version `PyJWT==2.0.0` works fine on `PyJWT==1.7.1`

## Expected Result

No Result.

## Actual Result

```File "D:\Softwares\Python37\lib\site-packages\graphql_jwt\shortcuts.py", line 16, in get_token
    return jwt_settings.JWT_ENCODE_HANDLER(payload, context)
  File "D:\Softwares\Python37\lib\site-packages\graphql_jwt\utils.py", line 40, in jwt_encode
    jwt_settings.JWT_ALGORITHM,
graphql.error.located_error.GraphQLLocatedError: 'str' object has no attribute 'decode'```

**Comment by dedayoa** [comment]
hi @RakeshRam. Appears the API's changed between 1.7.1 and 2.0.0. Django-graphql-jwt is setup to use 'PyJWT>=1.5.0' https://github.com/flavors/django-graphql-jwt/blob/28e4f9749bac839d327914cfdda2ea3bb77bd775/setup.py#L41
You probably want to report this in that project instead.

**Comment by auvipy** [comment]
those packages need pyjwt 2.0 support
